CREATE TABLE platform (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    platform VARCHAR2(50) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE client (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    birthdate DATE NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE game (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(200) NOT NULL,
    producer VARCHAR2(200) NOT NULL,
    director VARCHAR2(200) NOT NULL,
    launch_date DATE NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE platform_game (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    game_id NUMBER NOT NULL,
    platform_id NUMBER NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(game_id) REFERENCES game(id),
    FOREIGN KEY(platform_id) REFERENCES platform(id)
);

CREATE TABLE protagonist (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    protagonist_name VARCHAR(200) NOT NULL,
    game_id NUMBER NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(game_id) REFERENCES game(id)
);

CREATE TABLE game_copy (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    platform_game_id NUMBER NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(platform_game_id) REFERENCES platform_game(id)
);

CREATE TABLE rental (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    client_id NUMBER NOT NULL,
    game_copy_id NUMBER NOT NULL,
    rental_date DATE DEFAULT(SYSDATE) NOT NULL,
    return_date DATE,
    price NUMBER NOT NULL,
    returned NUMBER DEFAULT (0) NOT NULL CHECK (returned IN (1, 0)),
    PRIMARY KEY(id),
    FOREIGN KEY(client_id) REFERENCES client(id),
    FOREIGN KEY(game_copy_id) REFERENCES game_copy(id),
    UNIQUE (game_copy_id, client_id, rental_date)
);
